PL/Models/ErrorViewModel.cs
namespace PL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PL/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult GetAll()
        {
            ML.Result result = BL.Cliente.GetAll();
            ML.Cliente cliente = new ML.Cliente() { Clientes = result.Objects };
            return View(cliente);
        }
        public IActionResult Form(int? codCliente)
        {
            ML.Result resultEstadoCivil = BL.EstadoCivil.GetAll();
            ML.Result resultNacionalidad = BL.Nacionalidad.GetAll();
            ML.Cliente cliente = new ML.Cliente();
            if (codCliente != null)
            {
                ML.Result result = BL.Cliente.GetById(codCliente.Value);
                cliente = (ML.Cliente)result.Object;
            }
            cliente.EstadoCivil.Estados = resultEstadoCivil.Objects;
            cliente.Nacionalidad.Nacionalidades = resultNacionalidad.Objects;
            return View(cliente);
        }
        [HttpPost]
        public IActionResult Form(ML.Cliente cliente)
        {
            if(cliente.CodCliente == 0)
            {
                ML.Result result = BL.Cliente.Add(cliente);
                ViewBag.Mensaje = result.Correct ? "Cliente agregado correctamente." : "Error al registrar el cliente.";
            }
            else
            {
                ML.Result result = BL.Cliente.Update(cliente);
                ViewBag.Mensaje = result.Correct ? "Cliente actualizado correctamente." : "Error al actualizar el cliente.";
            }
            return PartialView("Modal");
        }
        public IActionResult Delete(int codCliente)
        {
            ML.Result result = BL.Cliente.Delete(codCliente);
            ViewBag.Mensaje = result.Correct ? "Cliente eliminado correctamente." : "Error al eliminar el cliente.";
            return PartialView("Modal");
        }
    }
}

PL/Controllers/CreditoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class CreditoController : Controller
    {
        public IActionResult GetByCodCliente(int codCliente)
        {
            ML.Result resultCreditos = BL.Credito.GetByCodCliente(codCliente);
            ML.Result resultCliente = BL.Cliente.GetById(codCliente);
            ML.Cliente cliente = new ML.Cliente();
            cliente = (ML.Cliente)resultCliente.Object;
            cliente.Credito.Creditos = resultCreditos.Objects;
            return View(cliente);
        }
        public IActionResult Form(int codCliente)
        {
            ML.Cliente cliente = new ML.Cliente();
            cliente.CodCliente = codCliente;

            ML.Result resultTipos = BL.TipoCredito.GetAll();
            cliente.Credito.TipoCredito = new ML.TipoCredito();
            cliente.Credito.TipoCredito.Tipos = resultTipos.Objects;

            return View(cliente);
        }
        [HttpPost]
        public IActionResult Form(ML.Cliente cliente)
        {
            ML.Result result = BL.Credito.Add(cliente);
            ViewBag.Mensaje = result.Correct ? "Crédito registrado correctamente." : "Error al registrar el crédito.";
            ViewBag.CodCliente = cliente.CodCliente;
            return PartialView("Modal");
        }
        public IActionResult Delete(int codCliente, int codCredito)
        {
            ML.Result result = BL.Credito.Delete(codCredito);
            ViewBag.CodCliente = codCliente;
            ViewBag.Mensaje = result.Correct ? "Crédito eliminado correctamente." : "Error al eliminar el crédito.";
            return PartialView("Modal");
        }
    }
}

PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System.Diagnostics;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PL/Views/Cliente/Form.cshtml
@model ML.Cliente
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Formulario</h1>
<hr />
<div>
    @using (Html.BeginForm("Form", "Cliente", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(model => model.CodCliente)
        <div class="row">
            <div class="col col-3">
                <label>Nombre</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user"></i></span>
                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder = "Nombre" })
                </div>
            </div>
            <div class="col col-3">
                <label>Apellido paterno</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user"></i></span>
                    @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control", @placeholder = "Apellido paterno" })
                </div>
            </div>
            <div class="col col-3">
                <label>Apellido materno</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user"></i></span>
                    @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control", @placeholder = "Apellido materno" })
                </div>
            </div>
            <div class="col col-3">
                <label>Fecha de nacimiento</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-cake-candles"></i></span>
                    @Html.TextBoxFor(model => model.FechaNacimiento, "{0:yyyy-MM-dd}", new { @class = "form-control", @type="date" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col col-3">
                <label>Estado civil</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user"></i></span>
                    @Html.DropDownListFor(model => model.EstadoCivil.IdEstadoCivil, new SelectList(Model.EstadoCivil.Estados, "IdEstadoCivil", "Nombre"), "Selecciona una opción", new {@class="form-control"})
                </div>
            </div>
            <div class="col col-3">
                <label>Nacionalidad</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-regular fa-flag"></i></span>
                    @Html.DropDownListFor(model => model.Nacionalidad.IdNacionalidad, new SelectList(Model.Nacionalidad.Nacionalidades, "IdNacionalidad", "Nombre"), "Selecciona una opción", new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div>
            <a class="btn btn-danger" href="@Url.Action("GetAll", "Cliente")">Volver</a>
            <button class="btn btn-success" type="submit">Guardar</button>
        </div>
    }
</div>

PL/Views/Cliente/GetAll.cshtml
@model ML.Cliente
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Clientes</h1>
<hr />
<div>
    <p>Puedes agregar un nuevo cliente.</p>
    <a class="btn btn-success" href="@Url.Action("Form", "Cliente")">Nuevo cliente</a>
</div>
<hr />
<div class="container">
    @if(Model.Clientes != null)
    {
        if(Model.Clientes.Count > 0)
        {
            <table class="table table-dark table-hover text-center">
                <thead>
                    <tr>
                        <th>Créditos</th>
                        <th>Editar</th>
                        <th>Nombre</th>
                        <th>Apellido paterno</th>
                        <th>Apellido materno</th>
                        <th>Fecha de nacimiento</th>
                        <th>Estado civil</th>
                        <th>Nacionalidad</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(ML.Cliente cliente in Model.Clientes)
                    {
                        <tr>
                            <td><a class="btn btn-outline-info" href="@Url.Action("GetByCodCliente", "Credito", new { codCliente = cliente.CodCliente })"><i class="fa-solid fa-hand-holding-dollar"></i></a></td>
                            <td><a class="btn btn-outline-warning" href="@Url.Action("Form", "Cliente", new { codCliente = cliente.CodCliente })"><i class="fa-solid fa-user-pen"></i></a></td>
                            <td>@cliente.Nombre</td>
                            <td>@cliente.ApellidoPaterno</td>
                            <td>@cliente.ApellidoMaterno</td>
                            <td>@cliente.FechaNacimiento.ToString("dd-MM-yyyy")</td>
                            <td>@cliente.EstadoCivil.Nombre</td>
                            <td>@cliente.Nacionalidad.Nombre</td>
                            <td><a class="btn btn-outline-danger" onclick="return confirm('¿Seguro que quieres eliminar?')"><i class="fa-solid fa-circle-xmark"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div role="alert" class="alert alert-warning">No hay clientes registrados</div>
        }
    }
</div>

PL/Views/Cliente/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Continuar", "GetAll", "Cliente", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PL/Views/Credito/Form.cshtml
@model ML.Cliente
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Formulario de crédito</h1>
<hr />
<div>
    @using(Html.BeginForm("Form", "Credito", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(model => model.CodCliente)
        <div class="row">
            <div class="col col-3">
                <label>Tipo de crédito</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-credit-card"></i></span>
                    @Html.DropDownListFor(model => model.Credito.TipoCredito.IdTipoCredito, new SelectList(Model.Credito.TipoCredito.Tipos, "IdTipoCredito", "Nombre"), "Selecciona un tipo", new { @class="form-control"})
                </div>
            </div>
            <div class="col col-3">
                <label>Monto</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1">$</span>
                    @Html.TextBoxFor(model => model.Credito.Monto, new { @class = "form-control", @placeholder = "0.00" })
                </div>
            </div>
            <div class="col col-3">
                <label>Fecha de vencimiento</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-calendar-days"></i></span>
                    @Html.TextBoxFor(model => model.Credito.FechaVencimiento, "{0:yyyy-MM-dd}", new { @class = "form-control", @type="date" })
                </div>
            </div>
            <div class="col col-3">
                <br />
                <div class="form-check form-switch">
                    @Html.CheckBoxFor(model => model.Credito.Activo, new { @class = "form-check-input" })
                    <label class="form-check-label" for="flexSwitchCheckDefault">Activo</label>
                </div>
            </div>
        </div>
        <div>
            <a class="btn btn-danger" href="@Url.Action("GetByCodCliente", "Credito", new {codCliente = Model.CodCliente})">Volver</a>
            <button class="btn btn-success" type="submit">Guardar</button>
        </div>
    }
</div>

PL/Views/Credito/GetByCodCliente.cshtml
@model ML.Cliente
@{
    ViewData["Title"] = "GetByCodCliente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Creditos registrados</h1>
<hr />
<div class="row">
    <div class="col">
        <p>Registra un nuevo crédito</p>
        <a class="btn btn-success" href="@Url.Action("Form", "Credito", new { codCliente = Model.CodCliente})">Nuevo crédito</a>
        <a class="btn btn-danger" href="@Url.Action("GetAll", "Cliente")">Volver</a>
    </div>
</div>
<hr />
<div>
    @if(Model.Credito.Creditos != null)
    {
        <h4>Cliente: @Model.Nombre @Model.ApellidoPaterno @Model.ApellidoMaterno</h4>
        if(Model.Credito.Creditos.Count > 0)
        {
            <table class="table table-dark table-hover text-center">
                <thead>
                    <tr>
                        <th>CodCredito</th>
                        <th>Activo</th>
                        <th>Tipo</th>
                        <th>Inicio</th>
                        <th>Vencimiento</th>
                        <th>Monto</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(ML.Credito credito in Model.Credito.Creditos)
                    {
                        <tr>
                            <td>@credito.CodCredito</td>
                            <td>
                                @if (credito.Activo)
                                {
                                    <i class="fa-solid fa-circle-check" style="color: #008000;"></i>
                                }
                                else
                                {
                                    <i class="fa-solid fa-circle-xmark" style="color: #ff0000;"></i>
                                }
                            </td>
                            <td>@credito.TipoCredito.Nombre</td>
                            <td>@credito.FechaInicio.ToShortDateString()</td>
                            <td>@credito.FechaVencimiento.ToShortDateString()</td>
                            <td>$ @credito.Monto</td>
                            <td><a class="btn btn-outline-danger" href="@Url.Action("Delete", "Credito", new { codCliente = Model.CodCliente, codCredito = credito.CodCredito})"><i class="fa-solid fa-ban"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div role="alert" class="alert alert-warning">No tienes creditos registrados.</div>
        }
    }
    else
    {
        <div role="alert" class="alert alert-danger">No se ha podido consultar los creditos.</div>
    }
</div>

PL/Views/Credito/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Continuar", "GetByCodCliente", "Credito", new { codCliente = ViewBag.CodCliente }, htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="GetAll">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>